---

version: '3'

volumes:
  swordphish_config:

services:
  swordphish:
    container_name: swordphish
    image: swordphish
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - swordphish_config:/opt/swordphish/config
    links:
      - swordphish-mail
    command: './manage.py makemigrations && ./manage.py migrate && ./manage.py runserver'
    restart: on-failure
  celery:
    image: swordphish
    links:
      - swordphish-mail
    command: '/usr/local/bin/celery -A Swordphish worker -l info -B'
    restart: on-failure
  swordphish-mail:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"
    restart: on-failure
