# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-25 14:34
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_campaign_host_subdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='targets_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='host_subdomain',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='Only a-z, 0-9, - and ., must not end with a .', regex=b'^[-.a-z0-9]{0,200}(?<!\\.)$')]),
        ),
    ]
