# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-20 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20160225_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoustarget',
            name='attachment_opened_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anonymoustarget',
            name='form_submitted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anonymoustarget',
            name='link_clicked_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anonymoustarget',
            name='mail_opened_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anonymoustarget',
            name='reported_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
