# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-05-23 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20170523_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='timeout',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
