# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-07 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_template_timeout'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together=set([('key', 'value')]),
        ),
    ]
