# Generated by Django 2.0.8 on 2018-09-04 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_auto_20180307_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='campaign_type',
            field=models.CharField(choices=[('1', 'Simple'), ('2', 'With Attachment'), ('3', 'Fake Form'), ('4', 'Fake Ransomware')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='display_name',
            field=models.CharField(blank='True', max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Display name must not contains @', regex='^[^@]{1,100}$')]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='host_subdomain',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='Only a-z, 0-9, - and ., must not end with a .', regex='^[-.a-z0-9]{0,200}(?<!\\.)$')]),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('1', 'Not Started'), ('2', 'Running'), ('3', 'Finished')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('#1', 'Mail with link'), ('1', 'Mail with link template'), ('#2', 'Mail with attachment'), ('2', 'Mail with attachment template'), ('3', 'Attachment template'), ('#3', 'Action after click'), ('4', 'Redirection'), ('5', 'Awareness template'), ('6', 'Fake form template'), ('7', 'Fake ransomware template')], default=1, max_length=1),
        ),
    ]
