# Generated by Django 4.1 on 2022-08-17 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20180904_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='attachment_template',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_attachment', to='Main.template'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='fake_form',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_fake_form', to='Main.template'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='fake_ransom',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_fake_ransom', to='Main.template'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='from_domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_from_domain', to='Main.phishmaildomain'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='host_domain',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_host_domain', to='Main.phishmaildomain'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='mail_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_mail', to='Main.template'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='onclick_action',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_action', to='Main.template'),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_type',
            field=models.CharField(choices=[('#1', 'Mail with link'), ('1', 'Mail with link template'), ('#2', 'Mail with attachment'), ('2', 'Mail with attachment template'), ('3', 'Attachment template'), ('#3', 'Action after click'), ('4', 'Redirection'), ('5', 'Awareness template'), ('6', 'Fake form template'), ('7', 'Fake ransomware template')], default=1, max_length=2),
        ),
    ]
