# Generated by Django 2.0.12 on 2022-05-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_auto_20180904_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoustarget',
            name='sandbox_attachment_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anonymoustarget',
            name='sandbox_attachment_opened_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anonymoustarget',
            name='sandbox_link_clicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anonymoustarget',
            name='sandbox_link_clicked_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anonymoustarget',
            name='sandbox_mail_opened',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='anonymoustarget',
            name='sandbox_mail_opened_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
