# Generated by Django 4.2.11 on 2024-04-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_alter_campaign_attachment_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoustarget',
            name='autoclick_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
