# Generated by Django 4.2.11 on 2024-04-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_anonymoustarget_autoclick_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='phishmaildomain',
            name='enabled',
            field=models.BooleanField(default=True, help_text='Enable domain'),
        ),
    ]
