# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-30 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LocalUsers', '0002_phishmeuser_must_change_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['entity__name', 'name']},
        ),
        migrations.AlterModelOptions(
            name='swordphishuser',
            options={'ordering': ['user__last_name', 'user__first_name', 'user__email']},
        ),
    ]
