# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-07 15:22
from __future__ import unicode_literals

from django.db import migrations
from LocalUsers.models import SwordphishUser


def replace_usernames(apps, schema_editor):
	for s in SwordphishUser.objects.all():
		s.user.username = s.user.email.lower()
		s.user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('LocalUsers', '0003_auto_20170330_1608'),
    ]

    operations = [
    	migrations.RunPython(replace_usernames),
    ]
