# Generated by Django 2.0.8 on 2018-09-04 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalUsers', '0004_auto_20180307_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swordphishuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
