# Generated by Django 2.0.8 on 2018-09-05 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocalUsers', '0005_auto_20180904_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swordphishuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message="Expected phone number format: '+999999999'", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
